name: Master Branch Pipeline

on:
  push:
    branches: [ master ]  # 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Hello Message
        run: echo "Master branch pipeline successfully triggered!"
